### ISSUE TITLE
建议增加账号批量导入导出功能

### ISSUE THREAD

**Issue by LonGDikE** [Immortalt/imt-wanke-client#1]
如题，谢谢：）

**Comment by Immortalt** [comment]
这个功能我会加入的。在完成之前，现阶段你可以先通过这个方式：
账号的加密存储位置是：我的电脑\我的文档 下的
imt-wanke-settings.ini 文件。
你可以打开我的文档备份这个文件。
另外千万不用泄露这个文件。

**Comment by LonGDikE** [comment]
好的，多谢，昨天已经发现这个加密文件了：）

**Comment by Immortalt** [comment]
今天更新，已经完成
