### ISSUE TITLE
批量登陆用户名与密码分隔符建议换成空格

### ISSUE THREAD

**Issue by LonGDikE** [Immortalt/imt-wanke-client#15]
因为密码中可能有等号=导致出错，就像我的密码中都包含=号，谢谢

**Comment by Immortalt** [comment]
这个问题不存在的，用户名和密码的分割并不是通过“=”分割的，而是直接根据（手机号长度+1）开始取的密码。所以分隔符其实填什么都无所谓，不可能因为你说的原因出错。

**Comment by LonGDikE** [comment]
嗯，我当时验证一个账号提示出错，以为是分隔符的问题，目前看不是，应该是末行回车的问题，比如三个账号批量登陆，第三行如果没有回车，前两个登陆成功，第三个会提示登陆失败(-129)，如果有回车换行则三个都登陆成功，但会出现第四个错误的提示，一个账号及密码无回车换行同样
