### ISSUE TITLE
UPNP始终显示已禁用

### ISSUE THREAD

**Issue by shensmart** [Immortalt/imt-wanke-client#17]
我的路由器已经开启了UPNP，2台设备都显示禁用，我手工开启了4593 4594 4693端口，还是显示禁用，咋样才能不禁用呢

**Comment by Immortalt** [comment]
建议你加官方群，然后看一边群公告，常见问题都在里面了
群号：597799388

设备异常、UPNP失败？dcdn为0？正常现象！

upnp无法开启是迅雷的固件更新后的禁用调整，现阶段不影响挖矿的，都一样，迅雷现阶段只看带宽和硬盘大小。只要设备显示在线、硬盘有容量显示，就在正常挖矿！还有那个dcdn，是0还是1也是无所谓的！都一样！迅雷没有正式部署CDN！无所谓的！只看带宽和硬盘！
