### ISSUE TITLE
离线状态提醒有问题，经常误报

### ISSUE THREAD

**Issue by ylq2468** [Immortalt/imt-wanke-client#23]
经常提醒玩客云掉线，但是刷新一下又好了，实际查看玩客云也没有任何问题，且提醒掉线的玩客云不是同一台

**Comment by Immortalt** [comment]
不算误报。
状态都是迅雷给的。如果告诉你离线意味着迅雷认为你离线。
离线是真的。但是有时候可能只是掉线几秒。
对于这个问题会考虑采用离线10分钟后才进行提醒的方式解决。
