### ISSUE TITLE
1.49以后的邮箱通知bug

### ISSUE THREAD

**Issue by changqing95588** [Immortalt/imt-wanke-client#27]
每次打开软件和每天09.01：
server酱 都正常推送 昨日收入 和 蛋价浮动；
邮箱 只推送蛋价浮动 每次打开软件和每天09.01都不会推送昨日收入。

**Comment by Immortalt** [comment]
吓得我马上打开软件测试了一下，我这里好像是正常的。请问你有几台设备，qq多少，我们仔细聊

**Comment by Immortalt** [comment]
结论是要把发件邮箱加入联系人不然容易被拒收
