### ISSUE TITLE
设备离线确还显示在线，不过硬盘容量为暂无数据

### ISSUE THREAD

**Issue by pinocao1980** [Immortalt/imt-wanke-client#33]
![image](https://user-images.githubusercontent.com/34387385/33792877-b92a6f28-dce6-11e7-83df-0c5af360ff32.png)

**Comment by qfnuzlr** [comment]
应该是刷新的慢 重启后 过一段时间才能更新数据 么有app更新数据及时 迅速

**Comment by Immortalt** [comment]
之前是因为太灵敏才降低灵敏度的。最新版已经恢复灵敏度了，反正比app来灵敏，真正的可以反映出设备有没有连接到迅雷服务器（设备蓝灯只代表联网，app显示在线也不一定真正的在线，只有判断它连接迅雷服务器成功才是真正的在线）
