### ISSUE TITLE
玩客云已激活天数错误

### ISSUE THREAD

**Issue by qfnuzlr** [Immortalt/imt-wanke-client#34]
以前是正确的 这几天发现都变成了已激活1天 并且不再变化，右键重启玩客云时 没有选中
排序 自动变化 能不能设置固定排序或者根据ip或者根据手机号 等等

**Comment by Immortalt** [comment]
估计是迅雷改变了激活天数的api导致的，以后会修正，不显示天数，只显示是否激活。固定排序就是点击排序查找，默认排序，选择最后的不排序

**Comment by Immortalt** [comment]
我看了一下这天数时而正常时而变1。
错误的恐怕不是我的软件，而是迅雷的服务器。
