### ISSUE TITLE
有些网站搞云监工，能不能做个php

### ISSUE THREAD

**Issue by qfnuzlr** [Immortalt/imt-wanke-client#35]
能不能搞个php网站挂机监控源码或者asp+access的也可以。
网站可以24小时 运行 电脑一般不好一直开机
不过那些挂机网站，都是收费的。能搞到源码 放到自己的网站空间运行，安全性好些，关键免费。
你可以了解一下，http://myzqb.cn/

**Comment by Immortalt** [comment]
我当然可以做，这两天没空罢了。而且网页版安全性绝对没有客户端高的。
另外我怀疑你只是打广告，呵呵
