### ISSUE TITLE
UPNP状态显示错误

### ISSUE THREAD

**Issue by glbfor** [Immortalt/imt-wanke-client#38]
路由器明明开启了UPNP，但是软件内部仍然显示的是 disabled   已禁用。

**Comment by Immortalt** [comment]
这不是软件错误，是迅雷一个月前早禁用了所有玩客云的upnp功能。
这个功能和挖矿无关，不影响收益，不用管的。
回头我就把这一栏去掉。

**Comment by mrkpu8** [comment]
迅雷最新通知,提示在路由器开启UPNP.,可能情况有变.

**Comment by qfnuzlr** [comment]
4593 4594 4693端口映射 10月出使开启的 后来关闭了这几个端口的映射
最近开始挖矿了 9865  45456 53987 31154端口开始映射了

**Comment by Immortalt** [comment]
迅雷返回的信息是假的。已经取消显示
