### ISSUE TITLE
大神最近不更新源代码，能否更新一下版本历史啊？

### ISSUE THREAD

**Issue by auslin45** [Immortalt/imt-wanke-client#40]
_如果源代码最近不方便更新到github，能否更新一下版本历史，让我们知道每次更新了啥功能呗，要不然每次更新还得到处找有什么不同

**Comment by Immortalt** [comment]
我现在通过公众号和QQ群公告发布版本历史，请关注公众号时空不朽或者加一下QQ群

**Comment by Immortalt** [comment]
现在发了一个issue作为更新历史的展示之处

**Comment by auslin45** [comment]
大神辛苦了！
