### ISSUE TITLE
口袋已经开源 有人做出了 转账功能 不朽也来个吧

### ISSUE THREAD

**Issue by qfnuzlr** [Immortalt/imt-wanke-client#56]
http://www.wankeyun.cc/thread-182.htm
转载
目前已实现的功能：
一、链克口袋账户管理：导入、导出（备份）、删除
二、导入账户文件存放在根目录的“keystore”文件夹下
三、每次转赠需要输入密码，程序不保存，不传输您的密码
四、代码开源：https://github.com/ImbaQ/MyLinkToken
五、程序已实现链克转赠，并且无需实名，无需实名，无需实名！不管之前是使用国内还是内外app生成的口袋文件，不管之前是否实名过，导入口袋文件后都可以使用！！！！！
时间仓促，程序还很简陋，小编技术也有限，希望更多的大牛能加入到本项目一起开发完善，为链克发展添砖加瓦！！！
后期开发计划：
一期计划：完成全功能钱包
1、转赠历史记录查询
2、口袋别名设置
3、口袋二维码显示
4、口袋文件生成
二期计划：增强功能
1、口袋到账实时提醒
2、自定义常用转赠帐户并可设置别名
3、优化统计信息，完善收益、支出报表
三期计划：开发移动端
1、安卓app
2、苹果app
MyLinkToken源码地址：https://github.com/ImbaQ/MyLinkToken

**Comment by Immortalt** [comment]
开源是好事情。
不过第三方钱包的话，容易被人利用加入病毒盗取玩客币。
另外你这样打广告很不地道，呵呵
