### ISSUE TITLE
作者你好，想请教几个问题

### ISSUE THREAD

**Issue by pyzworld** [Immortalt/imt-wanke-client#8]
sign是怎么生成的
还有sessionid 从cookie中取出 从哪里来的
看了你的代码 没有用过c# 代码看起来头疼 。

**Comment by pyzworld** [comment]
想做个iOS的客户端 

sign是参数生成的签名？

**Comment by Immortalt** [comment]
没错，sign是参数生成的签名。
具体生成步骤很复杂，请看代码。
